Chart:
  Name: "Should_be_overriden"
argocd:
  secretName: "argocd-notifications-secret"
awsVaults:
  awsRegion: "eu-central-1"
  refreshInterval: 5s
  secretManager:
    #refreshInterval: 10s ### Override refresh interval
    #awsRegion: "eu-west-1" ### Override region
    awsSecretKeys:
      - 'FOO/Bar'

serviceAccount:
  create: false
  annotations: {}
  name: argocd-sa

