# Pre-commit Git hooks - Local Development Safeguard
#
# Benefits of pre-commit hooks:
# 1. Client-Side Validation:
#    - Catches issues BEFORE they reach CI/CD pipeline
#    - Immediate feedback without waiting for CI checks
#    - Prevents pushing non-compliant code to remote
#    - Validates entire codebase by default
#
# 2. Fast Development Cycle:
#    - Instant validation on commit
#    - No need to wait for CI pipeline to discover basic issues
#    - Saves time by catching formatting/linting issues early
#    - Full codebase validation ensures overall consistency
#
# 3. Consistent Code Quality:
#    - Enforces standards before code leaves your machine
#    - Terraform formatting, validation, and linting
#    - Documentation and security checks
#    - Maintains quality across entire codebase
#
# Best Practices:
# - CI always runs against entire codebase (--all-files) to eliminate all risks
# - Local commits can run on changed files for faster feedback
# - STRONGLY RECOMMENDED: Run `pre-commit run --all-files` before pushing
#   This ensures you catch any interdependency issues before CI
#   Currently, this is not available as a configuration option (or not found during development time), 
# and needs to check of Issues for the feature request
# To get started:
# 1. Install pre-commit: `pip install pre-commit`
# 2. Install hooks: `pre-commit install`
# 3. First run: `pre-commit run --all-files`
#
# CI/CD Integration:
# - Pre-commit runs in CI against the entire codebase
# - Provides additional verification layer
# - Ensures all developers run pre-commit checks consistently
# - Catches any issues that might slip through local checks
#
# Note: You can bypass hooks with `git commit --no-verify` if needed - it is not recommended and still will be checked in CI/CD

fail_fast: false

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --args=-json
          - --args=-no-color
          - --tf-init-args=-upgrade
      - id: terraform_docs
        args:
          - '--args=--config=.terraform-docs.yml'
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--format=compact'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
