image: alpine/git:latest
  
definitions:
  services:
    docker:
      memory: 1024
  
  steps:
    - step: &Push-to-GitHub
        name: Push code changes to GitHub
        services:
          - docker
        caches:
          - docker
        script:
          - cd ..
          - mkdir gh-repo
          - git clone $GITHUB_REPO gh-repo
          - cd build
          - git checkout $BITBUCKET_TAG
          - cp -r * ../gh-repo
          - cd ../gh-repo
          - git config user.email "cicd@bots.bitbucket.org"
          - git config user.name "cicd"
          - git add .
          - git commit -m "Release $BITBUCKET_TAG"
          - git tag $BITBUCKET_TAG -m "$BITBUCKET_TAG"
          - git push --follow-tags

pipelines:
  tags:
    v*:
      - step: *Push-to-GitHub
